Security upgrade in routes.py
kom-senapati/bot-verse pull request #17
Opened 2024-10-02 12:17 UTC by Deeptig9138

Input Validation Functions: Created separate functions to validate the username, email, and password format. This ensures that the input adheres to specific rules before further processing.
Input Sanitization with Bleach: Sanitized the chatbot name and prompt using bleach.clean() to prevent any potential XSS attacks. This is crucial for any user-generated content that will be rendered in the HTML.
User Query Sanitization: Similarly sanitized the user query input in the chatbot interaction method.
Feedback on Invalid Inputs: Provided user feedback for invalid inputs in the login and signup routes.
Use of Regular Expressions: Regular expressions are utilized to enforce constraints on usernames and emails, ensuring they are in the correct format.

2024-10-02 12:17 UTC, Deeptig9138 commented
done

2024-10-02 13:09 UTC, kom-senapati requested changes
Do these things and commit!

2024-10-02 13:09 UTC, kom-senapati commented on routes.py
> -    @app.route("/chatbot/<int:chatbot_id>/update", methods=["GET", "POST"])
Dont delete this route

2024-10-02 13:09 UTC, kom-senapati commented on routes.py
> -    @app.route("/logout")
Dont delete logout

2024-10-02 13:09 UTC, kom-senapati commented on routes.py
> -        if Chatbot.query.count() == 0:
Dont delete this if part

2024-10-02 13:09 UTC, kom-senapati commented on routes.py
> +import bleach  # Importing bleach for sanitizing inputs
Remove all these comments we dont need comments

2024-10-02 13:09 UTC, kom-senapati commented on routes.py
> +import bleach  # Importing bleach for sanitizing inputs
Also add this bleach to requirements.txt

2024-10-04 06:46 UTC, kom-senapati commented
Its been 2 days give updates

2024-10-09 13:26 UTC, kom-senapati commented
Are you working @Deeptig9138 ?

2024-10-11 11:46 UTC, closed without merging